### ISSUE TITLE
Использование графов для иллюстрации нод и топиков

### ISSUE THREAD

**Issue by PonomarevDA** [AleksDevEdu/ros_course#13]
Думаю, было бы неплохо иллюстрировать описание взаимодействие нод и топиков с помощью графов :)
Например, [в топике ***0_07_Names_Mapping***  в разделе Node remapping](https://github.com/KaiL4eK/ros_course/blob/master/Topics/0_07_Names_Mapping.md#node-remapping) к тексту можно добавить такую иллюстрацию.

![rgb_to_gray](https://user-images.githubusercontent.com/36133264/46821719-300edd80-cd92-11e8-99aa-dc5f6fddfdc2.png)

**Comment by KaiL4eK** [comment]
Спасибо! Добавил иллюстрации)
