### ISSUE TITLE
Добавить ссылки на видео к топикам

### ISSUE THREAD

**Issue by serykhelena** [AleksDevEdu/ros_course#17]

**Comment by serykhelena** [comment]
Видосы закончились (=

**Comment by PonomarevDA** [comment]
Коммит [#17 for Topic_0_02 and some fixes with Git ](https://github.com/KaiL4eK/ros_course/commit/5488efd24072ffa7551ffcf0dd3fef24aabd58ab) добавляет пункты `Пакеты в ROS` и `Почему ROS крут` с ссылками на одно и то же видео.
