### ISSUE TITLE
На melodic не устанавливается пакет turtlebot

### ISSUE THREAD

**Issue by PonomarevDA** [AleksDevEdu/ros_course#19]
**Проблема такая**: на melodic не удается продолжать курс, начиная с [середины топика 1_04](https://github.com/KaiL4eK/ros_course/blob/master/Topics/1_04_Gazebo_101.md#turtlebot-sample) из-за того, что не поддерживается пакет turtlebot. 
На kinetic все работало и устанавливался пакет так:
`sudo apt install ros-kinetic-turtlebot-gazebo`
На melodic, очевидно, kinetic пакет не установить. Но и следующая интуитивная команда
`sudo apt install ros-melodic-turtlebot-gazebo`
возвращает ошибку _E: Невозможно найти пакет_.
Провел небольшое расследование:
- На [wiki.ros в разделе про turtlebot](http://wiki.ros.org/turtlebot) есть информация только по indigo и kinetic, но нет про melodic.
- На [репозитории пакета turtlebot](https://github.com/turtlebot/turtlebot) в гитхабе заведено [открытое issue о релизе turtlebot на melodic](https://github.com/turtlebot/turtlebot/issues/272), но при этом есть также ветка с melodic.

В общем, пакет turrtlebot на melodic сейчас не поддерживается, либо он был как-то переименован (например, [turtlebot 3](http://wiki.ros.org/turtlebot3) ???). 

**Возможные решения проблемы**: 
1. Просто скачать и поставить пакет turtlebot с git'а с ветки melodic - но будет ли он работать?
2. Посмотреть в сторону других пакетов, может его переименовали, например turtlebot3.
3. Может я где-то накосячил :)

**Comment by KaiL4eK** [comment]
Решено, приглашаю к тестированию =)

**Comment by KaiL4eK** [comment]
@PonomarevDA  Если этот вопрос решили - закрывай)

**Comment by PonomarevDA** [comment]
Протестировал. Вроде все работает.
