### ISSUE TITLE
Внести дополнения в 1_Setup

### ISSUE THREAD

**Issue by serykhelena** [AleksDevEdu/ros_course#3]
В параграфе `Подготовка среды ROS`  
- из какой директории следует вызывать данную команду 
- принципиально ли это 
- как прописать строку в конец файла `~/.bashrc`. И какую строку.. не совсем понятно, было бы здорово уточнить (для тех, кто совсем в танке) 

В параграфе `Подготовка рабочего пространства (workspace)` 
- какую строку и как добавить её в файл `~/.bashrc`

**Comment by KaiL4eK** [comment]
> как прописать строку в конец файла ~/.bashrc. И какую строку.. не совсем понятно, было бы здорово уточнить (для тех, кто совсем в танке)

Там почти все строки одинаковы, разве нет?

**Comment by KaiL4eK** [comment]
Вроде поправил, достаточно?

**Comment by serykhelena** [comment]
Может в пункте `Проверка установки` написать, какой результат должен увидеть человек.... типа вот я проверила, а как узнать, что то, что я увидела - это правильно.. А хотя ты написал... но тот результат, что я вижу...не стыкуется с моей картиной мира...

**Comment by KaiL4eK** [comment]
Исправляю

**Comment by KaiL4eK** [comment]
Сделано
