### ISSUE TITLE
Очепятки в 2_Packages_Catkin

### ISSUE THREAD

**Issue by serykhelena** [AleksDevEdu/ros_course#4]
+ 2-й абзац `ваш ws инициализирован и виден В системе ROS`
+ после описания зависимостей, параграф `Внутри CMakeLists.txt ... ` -> `можно вытащить базовые КУСКИ на ... ` 
+ после этого параграфа, после : там не должно быть что-то ещё? Может поставить разделительные маркеры, а то как будто код не пропечатался (= 
+ в графе `В результате`  первый пункт `в формате .xml `
+ в графе `В результате`  второй пункт `Файл ..., так как именно он УКАЗЫВАЕТ ... `
+ в графе `В результате`  второй пункт `Файл ..., в свою очередь ... является скорее ОПИСАНИЕМ ... `

**Comment by KaiL4eK** [comment]
Поправишь? :sweat_smile:

**Comment by KaiL4eK** [comment]
> после этого параграфа, после : там не должно быть что-то ещё? Может поставить разделительные маркеры, а то как будто код не пропечатался (=

Вроде все есть..

**Comment by KaiL4eK** [comment]
> в графе В результате первый пункт в формате .xml

Зануда блок {
.xml - расширение файла, XML - формат файла
}

**Comment by KaiL4eK** [comment]
> 2-й абзац ваш ws инициализирован и виден В системе ROS

Дискуссионное замечание, конечно правильнее твой вариант, но исходный также можно применять)

**Comment by KaiL4eK** [comment]
Короче исправляю)

**Comment by KaiL4eK** [comment]
Я сделяль
