### ISSUE TITLE
Добавить пример файла .gitignore 

### ISSUE THREAD

**Issue by serykhelena** [AleksDevEdu/ros_course#5]
Может быть в заключении 2_Packages_Catkin добавить пример файла .gitignore для последнего пункта, в котором ты говоришь о размещении содержимого пакета в репозитории

**Comment by KaiL4eK** [comment]
А что в содержимом пакета надо игнорировать?

**Comment by KaiL4eK** [comment]
Все бинарники кладутся в build папки catkin_ws

**Comment by serykhelena** [comment]
Я не знаю что.... просто из твоих формулировок, я подумала, что нужно только что-то определённое хранить в репозитории, но что конкретно спрятано под завесой тайны (=

**Comment by KaiL4eK** [comment]
Хм, сейчас перечитаю)

**Comment by serykhelena** [comment]
По-моему пока можно так оставить как есть (= Звучит очень даже прилично (=
