### ISSUE TITLE
Добавить немного уточнений в 3_Nodes_Topics

### ISSUE THREAD

**Issue by serykhelena** [AleksDevEdu/ros_course#6]
В части, где описывается запуск 3-х узлов, может быть добавить описание параметров, например 
rosrun - запуск... rospy_tutorials - имя __name:= ... - что-то ещё... 
Просто я не уверена, что корректно напишу ...

**Comment by KaiL4eK** [comment]
Опиши, как понимаешь)

**Comment by serykhelena** [comment]
Я сейчас ещё раз посмотрела....и теперь не понимаю как ещё подробнее можно это описать, поэтому закрываю (=
