### ISSUE TITLE
4_Names_Mapping - Node namespace

### ISSUE THREAD

**Issue by serykhelena** [AleksDevEdu/ros_course#7]
Ты предлагаешь запустить узел talker c аргументом __ns:=my_ns
Я запускаю, но особо апокалипсиса не наблюдаю... может поподробнее указать, что должно испугать человека?

**Comment by KaiL4eK** [comment]
Ну, видно же, что топик имеет уже другое имя, или нет?

**Comment by serykhelena** [comment]
Да, я потом уже увидела ... здесь тебе решать(: может быть и не нужно менять ничего

**Comment by serykhelena** [comment]
Просто у тебя там так расписано, что ожидаешь, что ноут воспламенится и сам побежит себя тушить (;

**Comment by KaiL4eK** [comment]
Вот добавил строчку, на что обратить внимание =)

**Comment by serykhelena** [comment]
Божественно (=
